language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4.1
  - ruby-head
cache: bundler
sudo: false
services:
  - mongodb
addons:
  code_climate:
    repo_token: 7ad1669579fa30cd29c63733f3b4a70a7f50b194f4002240f31ee75a1b10d011
after_success:
  - bundle exec codeclimate-test-reporter
